### ISSUE TITLE
NicheDE for DE analysis between two slides

### ISSUE THREAD

**Issue by Lixinyoung** [Kmason23/NicheDE#1]
I wonder if it possible to compare same index cell between two slides with different conditioning?
Like a same region from two different mice treated differently (Gene KnockOut vs Control), I want to know a same group, such as the Fibroblasts(index) next to Astrocytes(niche) , whether has differences between two conditions.

I know I can use `MergeObjects()` to merge two batches, how can I make a DE between batches?

Thanks

**Comment by Kmason23** [comment]
Hello,

Each niche-DE object contains the regression coefficients and the corresponding standard errors corresponding to each index-niche pair for each gene (e.g.fibroblasts near astrocytes). You could use these values to implement your own contrast test which would tell you if the two groups have significant differences. If you would like to discuss this idea further, please contact me at kaishu@wharton.upenn.edu
