### ISSUE TITLE
RCTD deconvolution fractions

### ISSUE THREAD

**Issue by istvankleijn** [Kmason23/NicheDE#2]
Thanks for developing this package, it looks really cool and useful! I have a question about the deconvolution matrix required for Visium analysis. 
Do I understand correctly from the paper methods that cell type fractions are used when estimating the number of cells in each spot? So in order to use RCTD output, I would need to convert the UMI proportions first to cell type fractions like suggested in https://github.com/dmcable/spacexr/issues/108#issuecomment-1263553481?

**Comment by Kmason23** [comment]
Hi,
I'm not sure what they meant by non-normalized weight matrix. In the both the methods section of the RCTD paper as well as [here](https://github.com/dmcable/spacexr/issues/45), they note that they are estimating the cell type proportion per spot. NicheDE then uses the cell type specific library size to estimate the total number of cells. You should use the regular RCTD output in the results slot and using that are input to NicheDE.

**Comment by Kmason23** [comment]
I see, then yes cell type normalization would be appropriate. Thank you for the information and I will add the necessary code to the vignette shortly. In the meantime, I would suggest using CellTrek for deconvolution which in my experience has given very reasonable results.

**Comment by istvankleijn** [comment]
Thanks for the clarification and updated docs, I'll give that a go! I'll also look into CellTrek which I had not heard of before.
